//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocios {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensagensLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensLog() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Negocios.MensagensLog", typeof(MensagensLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contrato $Contrato gerado..
        /// </summary>
        internal static string L0001 {
            get {
                return ResourceManager.GetString("L0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro $NomeCompleto, Id $ID incluido..
        /// </summary>
        internal static string L0002 {
            get {
                return ResourceManager.GetString("L0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa  $NomeCompleto, Id $ID, vinculada ao Contrato $Contrato, como titular.
        /// </summary>
        internal static string L0003 {
            get {
                return ResourceManager.GetString("L0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa  $NomeCompleto, Id $ID, vinculada ao Contrato $Contrato, como dependente.
        /// </summary>
        internal static string L0004 {
            get {
                return ResourceManager.GetString("L0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato $Contato, Id $ID, incluido..
        /// </summary>
        internal static string L0005 {
            get {
                return ResourceManager.GetString("L0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato $Contato, Id $ID, excluido..
        /// </summary>
        internal static string L0006 {
            get {
                return ResourceManager.GetString("L0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa  $NomeCompleto, Id $ID, canceladado  Contrato $Contrato..
        /// </summary>
        internal static string L0007 {
            get {
                return ResourceManager.GetString("L0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato $Contrato, Id $ID, cancelado..
        /// </summary>
        internal static string L0008 {
            get {
                return ResourceManager.GetString("L0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerada parcela $ID, em $DATAEMISSAO, com vencimento em $VENCIMENTO, no valor de R$ $VALOR..
        /// </summary>
        internal static string L0009 {
            get {
                return ResourceManager.GetString("L0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerado boleto da parcela $ID..
        /// </summary>
        internal static string L0010 {
            get {
                return ResourceManager.GetString("L0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parcela  $ID, via importação..
        /// </summary>
        internal static string L0011 {
            get {
                return ResourceManager.GetString("L0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cartão $CARTAO gerado..
        /// </summary>
        internal static string L0012 {
            get {
                return ResourceManager.GetString("L0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato $Conttato, Id $ID, Ativado.
        /// </summary>
        internal static string L0013 {
            get {
                return ResourceManager.GetString("L0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parcela $ID Cancelada..
        /// </summary>
        internal static string L0014 {
            get {
                return ResourceManager.GetString("L0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato $Contrato, Id $ID, ativado..
        /// </summary>
        internal static string L0015 {
            get {
                return ResourceManager.GetString("L0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento do CPF [{0}] , no valor de [{1}] , com vencimento em [{2}] , importado..
        /// </summary>
        internal static string L0016 {
            get {
                return ResourceManager.GetString("L0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerado cartões em massa..
        /// </summary>
        internal static string L0017 {
            get {
                return ResourceManager.GetString("L0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento [{0}] , vinculado com a parcela [{1}] , contrato [{2}]  atualizado (Via Importação).
        /// </summary>
        internal static string L0018 {
            get {
                return ResourceManager.GetString("L0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status do dependente [{0}] , alterado para [{1}]  ( Validando Geração Status Cartão)..
        /// </summary>
        internal static string L0019 {
            get {
                return ResourceManager.GetString("L0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unidade $Unidade cadastrada..
        /// </summary>
        internal static string L0020 {
            get {
                return ResourceManager.GetString("L0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cartão [{0}]  enviado para impressão..
        /// </summary>
        internal static string L0021 {
            get {
                return ResourceManager.GetString("L0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cartão [{0}] retornou da impressão..
        /// </summary>
        internal static string L0022 {
            get {
                return ResourceManager.GetString("L0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cartão [{0}]  entregue para [{1}].
        /// </summary>
        internal static string L0023 {
            get {
                return ResourceManager.GetString("L0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cartão [{0}]  gerado manualmente / Parcela confirmada pagamento manualmente..
        /// </summary>
        internal static string L0024 {
            get {
                return ResourceManager.GetString("L0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato $Contrato alterado..
        /// </summary>
        internal static string L0025 {
            get {
                return ResourceManager.GetString("L0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unidade $Unidade atualizada.
        /// </summary>
        internal static string L0026 {
            get {
                return ResourceManager.GetString("L0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelada(s) parcelas pendentes do contrato $Contrato.
        /// </summary>
        internal static string L0027 {
            get {
                return ResourceManager.GetString("L0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Baixa manual parcela &apos;{0}&apos;.
        /// </summary>
        internal static string L0028 {
            get {
                return ResourceManager.GetString("L0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contrato Familiar Corporativo [{0}]  Cadastrado/Vinculado ao Contrato Corporativo [{1}].
        /// </summary>
        internal static string L0029 {
            get {
                return ResourceManager.GetString("L0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Colaborador [{0}]  vinculado ao plano Corporativo [{1}].
        /// </summary>
        internal static string L0030 {
            get {
                return ResourceManager.GetString("L0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterado ponto de venda para id [{0}] ..
        /// </summary>
        internal static string L0031 {
            get {
                return ResourceManager.GetString("L0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contrato inicial gravado no historico..
        /// </summary>
        internal static string L0032 {
            get {
                return ResourceManager.GetString("L0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dependente [{0}]  inativado..
        /// </summary>
        internal static string L0033 {
            get {
                return ResourceManager.GetString("L0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vs do contrato atualizada [VS: {0} ].
        /// </summary>
        internal static string L0034 {
            get {
                return ResourceManager.GetString("L0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contrato  {0} esta sendo editado..
        /// </summary>
        internal static string L0035 {
            get {
                return ResourceManager.GetString("L0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario ID {0}  [{1}] alterou sua propria senha..
        /// </summary>
        internal static string L0036 {
            get {
                return ResourceManager.GetString("L0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento via cartão vinculado a parcela  {0}.
        /// </summary>
        internal static string L0037 {
            get {
                return ResourceManager.GetString("L0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativado integrantes do contrato / (Gerado cartões).
        /// </summary>
        internal static string L0038 {
            get {
                return ResourceManager.GetString("L0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano da parcela {0} alterado manualmente para {1}.
        /// </summary>
        internal static string L0039 {
            get {
                return ResourceManager.GetString("L0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parcela {0} unida a parcela {1}..
        /// </summary>
        internal static string L0040 {
            get {
                return ResourceManager.GetString("L0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Emissao alterada (parcela {0})..
        /// </summary>
        internal static string L0041 {
            get {
                return ResourceManager.GetString("L0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Vencimenta altarada (parcela {0})..
        /// </summary>
        internal static string L0042 {
            get {
                return ResourceManager.GetString("L0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor da adesão alterada (parcela {0})..
        /// </summary>
        internal static string L0043 {
            get {
                return ResourceManager.GetString("L0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Pagamento alterada (parcela {0})..
        /// </summary>
        internal static string L0044 {
            get {
                return ResourceManager.GetString("L0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterado forma de pagamento (parcela {0}).
        /// </summary>
        internal static string L0045 {
            get {
                return ResourceManager.GetString("L0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição do produto ligada a parcela alterado (parcela {0}).
        /// </summary>
        internal static string L0046 {
            get {
                return ResourceManager.GetString("L0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterado valor de desconto do produto {0} referente parcela {1}.
        /// </summary>
        internal static string L0047 {
            get {
                return ResourceManager.GetString("L0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterado valor total da parcela  {0}.
        /// </summary>
        internal static string L0048 {
            get {
                return ResourceManager.GetString("L0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parcela {0} baixa manual pelo financeiro..
        /// </summary>
        internal static string L0049 {
            get {
                return ResourceManager.GetString("L0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validade do contrato contrato {0}, alterada [Parcelas não pagas foram canceladas] .
        /// </summary>
        internal static string L0050 {
            get {
                return ResourceManager.GetString("L0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parcela {0} cancelada..
        /// </summary>
        internal static string L0051 {
            get {
                return ResourceManager.GetString("L0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parcela {0} teve sua data de vencimento alterada para {1}..
        /// </summary>
        internal static string L0052 {
            get {
                return ResourceManager.GetString("L0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contrato Corporativo Familiar, desvinculado do plano Corporativo.
        /// </summary>
        internal static string L0053 {
            get {
                return ResourceManager.GetString("L0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parcela {0} do corporativo {1} emitida..
        /// </summary>
        internal static string L0054 {
            get {
                return ResourceManager.GetString("L0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parcelas Geradas {0}.
        /// </summary>
        internal static string L0055 {
            get {
                return ResourceManager.GetString("L0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Forma de pagamento da parcela {0} alterada..
        /// </summary>
        internal static string L0056 {
            get {
                return ResourceManager.GetString("L0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assinatura vinculada ao contrato..
        /// </summary>
        internal static string L0057 {
            get {
                return ResourceManager.GetString("L0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contrato {0} cancelado. Motivo {1}, descrição {2}.
        /// </summary>
        internal static string L0058 {
            get {
                return ResourceManager.GetString("L0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contrato cancelado via pagamento de parcela de cancelamento..
        /// </summary>
        internal static string L0059 {
            get {
                return ResourceManager.GetString("L0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto {0} da parcela {1} teve desconto alterado para {2}.
        /// </summary>
        internal static string L0060 {
            get {
                return ResourceManager.GetString("L0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anotação {0} incluida..
        /// </summary>
        internal static string L0061 {
            get {
                return ResourceManager.GetString("L0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status da parcela {0} foi alterado para {1}.
        /// </summary>
        internal static string L0062 {
            get {
                return ResourceManager.GetString("L0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aterado ciclo da parcela {0}.
        /// </summary>
        internal static string L0063 {
            get {
                return ResourceManager.GetString("L0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterado ciclo do contrato {0}.
        /// </summary>
        internal static string L0064 {
            get {
                return ResourceManager.GetString("L0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validade do contrato alterado {0} - {1}.
        /// </summary>
        internal static string L0065 {
            get {
                return ResourceManager.GetString("L0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterado data vencimento para {0} da parcela {0}.
        /// </summary>
        internal static string L0066 {
            get {
                return ResourceManager.GetString("L0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parcela {0} foi abonada da adesão..
        /// </summary>
        internal static string L0067 {
            get {
                return ResourceManager.GetString("L0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Local de cadastro alteado {0}.
        /// </summary>
        internal static string L0068 {
            get {
                return ResourceManager.GetString("L0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário {0} foi bloqueado no ponto de venda {1}.
        /// </summary>
        internal static string L0069 {
            get {
                return ResourceManager.GetString("L0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comissão da parcela {0} referente ao contrato {1} processada..
        /// </summary>
        internal static string L0070 {
            get {
                return ResourceManager.GetString("L0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comissão do ponto de venda {0} atualizado..
        /// </summary>
        internal static string L0071 {
            get {
                return ResourceManager.GetString("L0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados pessoa fisica id {0} Nome {1} alterado, segue alterações {2}.
        /// </summary>
        internal static string L0072 {
            get {
                return ResourceManager.GetString("L0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contrato {0} negociado. [Parcelas vencidas foram canceladas.].
        /// </summary>
        internal static string L0073 {
            get {
                return ResourceManager.GetString("L0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Emitido boleto {0} via negociação..
        /// </summary>
        internal static string L0074 {
            get {
                return ResourceManager.GetString("L0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parcela {0} baixada via importação do arquivo de remessa..
        /// </summary>
        internal static string L0075 {
            get {
                return ResourceManager.GetString("L0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contezino {0} teve sua senha dadastrada via sistema interno..
        /// </summary>
        internal static string L0076 {
            get {
                return ResourceManager.GetString("L0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contezino {0} teve sua senha alterada via sistema interno..
        /// </summary>
        internal static string L0077 {
            get {
                return ResourceManager.GetString("L0077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa {0} liberada para acesso ao contrato {1} do parceiro.
        /// </summary>
        internal static string L0078 {
            get {
                return ResourceManager.GetString("L0078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edição do contrato {0}, foi finalizada pelo usuário {1}.
        /// </summary>
        internal static string L0079 {
            get {
                return ResourceManager.GetString("L0079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contrato {0} reativado..
        /// </summary>
        internal static string L0080 {
            get {
                return ResourceManager.GetString("L0080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluido produto {0} de forma manual na parcela {1}.
        /// </summary>
        internal static string L0081 {
            get {
                return ResourceManager.GetString("L0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campanha {0} teve seu canal SMS atualizado..
        /// </summary>
        internal static string L0082 {
            get {
                return ResourceManager.GetString("L0082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contrato foi contemplado com o premio {0}.
        /// </summary>
        internal static string L0083 {
            get {
                return ResourceManager.GetString("L0083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mensagem/campanha do contrato {0} foi excluida.
        /// </summary>
        internal static string L0084 {
            get {
                return ResourceManager.GetString("L0084", resourceCulture);
            }
        }
    }
}
