//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Portal.Negocios.WSLogin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LoginSoap", Namespace="http://tempuri.org/")]
    public partial class Login : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AcessoUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Login() {
            this.Url = global::Portal.Negocios.Properties.Settings.Default.Portal_Negocios_WSLogin_Login;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AcessoUsuarioCompletedEventHandler AcessoUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AcessoUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AcessoUsuarioController AcessoUsuario(string chaveUsuario, string cnpjParceiro, string senhaParceiro) {
            object[] results = this.Invoke("AcessoUsuario", new object[] {
                        chaveUsuario,
                        cnpjParceiro,
                        senhaParceiro});
            return ((AcessoUsuarioController)(results[0]));
        }
        
        /// <remarks/>
        public void AcessoUsuarioAsync(string chaveUsuario, string cnpjParceiro, string senhaParceiro) {
            this.AcessoUsuarioAsync(chaveUsuario, cnpjParceiro, senhaParceiro, null);
        }
        
        /// <remarks/>
        public void AcessoUsuarioAsync(string chaveUsuario, string cnpjParceiro, string senhaParceiro, object userState) {
            if ((this.AcessoUsuarioOperationCompleted == null)) {
                this.AcessoUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcessoUsuarioOperationCompleted);
            }
            this.InvokeAsync("AcessoUsuario", new object[] {
                        chaveUsuario,
                        cnpjParceiro,
                        senhaParceiro}, this.AcessoUsuarioOperationCompleted, userState);
        }
        
        private void OnAcessoUsuarioOperationCompleted(object arg) {
            if ((this.AcessoUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcessoUsuarioCompleted(this, new AcessoUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AcessoUsuarioController {
        
        private string cpfCnpjUsuarioField;
        
        private string nomeUsuarioField;
        
        private string[] cnpjPlanosField;
        
        /// <remarks/>
        public string CpfCnpjUsuario {
            get {
                return this.cpfCnpjUsuarioField;
            }
            set {
                this.cpfCnpjUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string NomeUsuario {
            get {
                return this.nomeUsuarioField;
            }
            set {
                this.nomeUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string[] CnpjPlanos {
            get {
                return this.cnpjPlanosField;
            }
            set {
                this.cnpjPlanosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AcessoUsuarioCompletedEventHandler(object sender, AcessoUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AcessoUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcessoUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AcessoUsuarioController Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AcessoUsuarioController)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591