//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContezaAdmin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensagensDoSistema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensDoSistema() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContezaAdmin.MensagensDoSistema", typeof(MensagensDoSistema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo $Campo não pode ser nulo..
        /// </summary>
        internal static string _0001 {
            get {
                return ResourceManager.GetString("_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum usuário encontrado, verifique a digitação e tente novamente..
        /// </summary>
        internal static string _0002 {
            get {
                return ResourceManager.GetString("_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login inativo no sistema..
        /// </summary>
        internal static string _0003 {
            get {
                return ResourceManager.GetString("_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data informada não pode ser inferior a data atual..
        /// </summary>
        internal static string _0004 {
            get {
                return ResourceManager.GetString("_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP não encontrado..
        /// </summary>
        internal static string _0005 {
            get {
                return ResourceManager.GetString("_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titúlar não pode ser menor de idade..
        /// </summary>
        internal static string _0006 {
            get {
                return ResourceManager.GetString("_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum plano encontrado para esta combinação, entre em contato com o comercial..
        /// </summary>
        internal static string _0007 {
            get {
                return ResourceManager.GetString("_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe parcela anterior a selecionada..
        /// </summary>
        internal static string _0008 {
            get {
                return ResourceManager.GetString("_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As duas parcelas devem estar com status livre para vinculo..
        /// </summary>
        internal static string _0009 {
            get {
                return ResourceManager.GetString("_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma parcela para aplicar o desconto..
        /// </summary>
        internal static string _0010 {
            get {
                return ResourceManager.GetString("_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente parcelas não emitidas podem sofrer desconto, procure o departamento financeiro..
        /// </summary>
        internal static string _0011 {
            get {
                return ResourceManager.GetString("_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este CPF/CNPJ esta já esta vinculado a um contrato, deseja abrir o contrato?.
        /// </summary>
        internal static string _0012 {
            get {
                return ResourceManager.GetString("_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular alterado com sucesso..
        /// </summary>
        internal static string _0013 {
            get {
                return ResourceManager.GetString("_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido incluir dependentes em contratos inadimplentes..
        /// </summary>
        internal static string _0014 {
            get {
                return ResourceManager.GetString("_0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ative o contrato antes de poder incluir dependentes..
        /// </summary>
        internal static string _0015 {
            get {
                return ResourceManager.GetString("_0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato bloqueado, entre em contato com o financeiro..
        /// </summary>
        internal static string _0016 {
            get {
                return ResourceManager.GetString("_0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro incluido com sucesso..
        /// </summary>
        internal static string _0017 {
            get {
                return ResourceManager.GetString("_0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro atualizado com sucesso..
        /// </summary>
        internal static string _0018 {
            get {
                return ResourceManager.GetString("_0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser selecionado um plano para geração das parcelas..
        /// </summary>
        internal static string _0019 {
            get {
                return ResourceManager.GetString("_0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcelas já emitidas não podem ser alteradas..
        /// </summary>
        internal static string _0020 {
            get {
                return ResourceManager.GetString("_0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela já paga..
        /// </summary>
        internal static string _0021 {
            get {
                return ResourceManager.GetString("_0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela cancelada..
        /// </summary>
        internal static string _0022 {
            get {
                return ResourceManager.GetString("_0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de pagamento não pode ser maior que data corrente..
        /// </summary>
        internal static string _0023 {
            get {
                return ResourceManager.GetString("_0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do pagamento não pode ser menor que o valor da parcela..
        /// </summary>
        internal static string _0024 {
            get {
                return ResourceManager.GetString("_0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela atualizada com sucesso..
        /// </summary>
        internal static string _0025 {
            get {
                return ResourceManager.GetString("_0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependente cancelado..
        /// </summary>
        internal static string _0026 {
            get {
                return ResourceManager.GetString("_0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato cancelado, lembre-se de confirmar cancelamento dos boletos ha vencer..
        /// </summary>
        internal static string _0027 {
            get {
                return ResourceManager.GetString("_0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem parcelas com status de gerada para serem emitidas..
        /// </summary>
        internal static string _0028 {
            get {
                return ResourceManager.GetString("_0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessario gerar o contrato antes de continuar..
        /// </summary>
        internal static string _0029 {
            get {
                return ResourceManager.GetString("_0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Status deste contrato impede mudanças no mesmo. .
        /// </summary>
        internal static string _0030 {
            get {
                return ResourceManager.GetString("_0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF informado é invalido..
        /// </summary>
        internal static string _0031 {
            get {
                return ResourceManager.GetString("_0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP Invalido..
        /// </summary>
        internal static string _0032 {
            get {
                return ResourceManager.GetString("_0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependente na lista para inativar. Favor gerar novas parcelas e emitir a alteração de contrato para finalizar o processo.
        /// </summary>
        internal static string _0034 {
            get {
                return ResourceManager.GetString("_0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato cancelado, o mesmo deve ser ativado novamente..
        /// </summary>
        internal static string _0035 {
            get {
                return ResourceManager.GetString("_0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato ativo, incluir dependente ira acarretar na geração de novas parcelas..
        /// </summary>
        internal static string _0036 {
            get {
                return ResourceManager.GetString("_0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem documentos para serem exibidos.
        /// </summary>
        internal static string _0037 {
            get {
                return ResourceManager.GetString("_0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As parcelas devem ser salvas para constarem no termo..
        /// </summary>
        internal static string _0038 {
            get {
                return ResourceManager.GetString("_0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela selecionada já foi paga, deseja confirmar?.
        /// </summary>
        internal static string _0039 {
            get {
                return ResourceManager.GetString("_0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF já cadastrado..
        /// </summary>
        internal static string _0040 {
            get {
                return ResourceManager.GetString("_0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo parceiro atualizado..
        /// </summary>
        internal static string _0041 {
            get {
                return ResourceManager.GetString("_0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este cartão já foi entregue.
        /// </summary>
        internal static string _0042 {
            get {
                return ResourceManager.GetString("_0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato deve ser gerado antes de incluir o cartão..
        /// </summary>
        internal static string _0043 {
            get {
                return ResourceManager.GetString("_0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão já gerado não pode ser editado..
        /// </summary>
        internal static string _0044 {
            get {
                return ResourceManager.GetString("_0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão já cadastrado para $NOME, id $ID..
        /// </summary>
        internal static string _0045 {
            get {
                return ResourceManager.GetString("_0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão gerado com sucesso, favor enviar para impressão..
        /// </summary>
        internal static string _0046 {
            get {
                return ResourceManager.GetString("_0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão do titular deve ser cadastrado primeiro..
        /// </summary>
        internal static string _0047 {
            get {
                return ResourceManager.GetString("_0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ Inválido.
        /// </summary>
        internal static string _0048 {
            get {
                return ResourceManager.GetString("_0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao cadastrar titular do contrato principal..
        /// </summary>
        internal static string _0049 {
            get {
                return ResourceManager.GetString("_0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A versão instalada neste equipamento é &apos;{0}&apos; desatualizada com relação a versão &apos;{1}&apos; mais nova, não atualizar a versão acarreta em erros de dados, favor REINICIAR O GESTOR, se o problema continuar, entre em contato com a TI..
        /// </summary>
        internal static string _0050 {
            get {
                return ResourceManager.GetString("_0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A versão do sistema foi atualizada, é necessario fechar e abrir o aplicativo novamente para atualização local..
        /// </summary>
        internal static string _0051 {
            get {
                return ResourceManager.GetString("_0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este CNPJ já esta cadastrado como sendo contrato corporativo.
        /// </summary>
        internal static string _0052 {
            get {
                return ResourceManager.GetString("_0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente cartões em status de gerados podem ser enviados para impressão..
        /// </summary>
        internal static string _0053 {
            get {
                return ResourceManager.GetString("_0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF Vinculado a um plano familiar. Deseja abrir o arquivo de ajuda?.
        /// </summary>
        internal static string _0054 {
            get {
                return ResourceManager.GetString("_0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor verificar a quantidade de caracteres no telefone informado..
        /// </summary>
        internal static string _0055 {
            get {
                return ResourceManager.GetString("_0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão de rede caiu, tente novamente..
        /// </summary>
        internal static string _0056 {
            get {
                return ResourceManager.GetString("_0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum arquivo de scanner encontrado..
        /// </summary>
        internal static string _0057 {
            get {
                return ResourceManager.GetString("_0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este contrato possui {0} parcelas em aberto, favor entrar em contato com a gerencia de atendimento..
        /// </summary>
        internal static string _0058 {
            get {
                return ResourceManager.GetString("_0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Senha&quot; e &quot;Confirmação da Nova Senha&quot; não são iguais, favor verificar a digitação..
        /// </summary>
        internal static string _0059 {
            get {
                return ResourceManager.GetString("_0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha alterada com sucesso..
        /// </summary>
        internal static string _0060 {
            get {
                return ResourceManager.GetString("_0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja desvincular o Nivel {0} da sessão {1} ?.
        /// </summary>
        internal static string _0061 {
            get {
                return ResourceManager.GetString("_0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um valor valido em {0}..
        /// </summary>
        internal static string _0062 {
            get {
                return ResourceManager.GetString("_0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor da parcela é menor que o minimo liberado..
        /// </summary>
        internal static string _0063 {
            get {
                return ResourceManager.GetString("_0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro não identificado, comando não foi executado..
        /// </summary>
        internal static string _0064 {
            get {
                return ResourceManager.GetString("_0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este CPF ja esta vinculado a este contrato corporativo.
        /// </summary>
        internal static string _0065 {
            get {
                return ResourceManager.GetString("_0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este CPF ja esta vinculado a este contrato corporativo {0}..
        /// </summary>
        internal static string _0066 {
            get {
                return ResourceManager.GetString("_0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este contrato possui parcelas em aberto que devem ser quitadas antes de vincular ao plano corporativo. {0}.
        /// </summary>
        internal static string _0067 {
            get {
                return ResourceManager.GetString("_0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este CPF esta vinculado a um plano familiar, deseja incorporar?.
        /// </summary>
        internal static string _0068 {
            get {
                return ResourceManager.GetString("_0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de validade do contrato alterada, todas as parcelas nãp pagas foram canceladas, necessario gerar novas parcelas..
        /// </summary>
        internal static string _0069 {
            get {
                return ResourceManager.GetString("_0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela cancelada..
        /// </summary>
        internal static string _0070 {
            get {
                return ResourceManager.GetString("_0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimento não pode ser menor que data de fechamento..
        /// </summary>
        internal static string _0071 {
            get {
                return ResourceManager.GetString("_0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status da parcela {0} impede que a mesma seja unida a outra parcela..
        /// </summary>
        internal static string _0072 {
            get {
                return ResourceManager.GetString("_0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma parcela para este vencimento..
        /// </summary>
        internal static string _0073 {
            get {
                return ResourceManager.GetString("_0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependente já consta no fluxo de cancelamento..
        /// </summary>
        internal static string _0074 {
            get {
                return ResourceManager.GetString("_0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependente já esta cancelado..
        /// </summary>
        internal static string _0075 {
            get {
                return ResourceManager.GetString("_0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de vencimento deve ser maior que data atual..
        /// </summary>
        internal static string _0076 {
            get {
                return ResourceManager.GetString("_0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este contrato se encontra em edição, favor finalizar o processo para gerar as parcelas..
        /// </summary>
        internal static string _0077 {
            get {
                return ResourceManager.GetString("_0077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato inativado.{0}A parcela foi Gerada, favor emitir a forma de pagamento.{1}Apos a baixa da parcela o contrato será efetivamente cancelado..
        /// </summary>
        internal static string _0078 {
            get {
                return ResourceManager.GetString("_0078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato cancelado..
        /// </summary>
        internal static string _0079 {
            get {
                return ResourceManager.GetString("_0079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela não pode mais ser editada..
        /// </summary>
        internal static string _0080 {
            get {
                return ResourceManager.GetString("_0080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para alterar uma parcela para o status de paga é necessario efetuar a baixa da parcela.
        /// </summary>
        internal static string _0081 {
            get {
                return ResourceManager.GetString("_0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação invalida, campo {0}..
        /// </summary>
        internal static string _0082 {
            get {
                return ResourceManager.GetString("_0082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor informado menor que o valor devido..
        /// </summary>
        internal static string _0083 {
            get {
                return ResourceManager.GetString("_0083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data nascimento {0} não pode ser maior que a data atual..
        /// </summary>
        internal static string _0084 {
            get {
                return ResourceManager.GetString("_0084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicio do contrato não pode ser superior que data atual..
        /// </summary>
        internal static string _0085 {
            get {
                return ResourceManager.GetString("_0085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fim do contrato não pode ser inferior a data de inicio do contrato..
        /// </summary>
        internal static string _0086 {
            get {
                return ResourceManager.GetString("_0086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor da parcela é inferior ao valor minimo permitido para esta forma de negociação, tente em menos parcelas ou outra simulação..
        /// </summary>
        internal static string _0087 {
            get {
                return ResourceManager.GetString("_0087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação só é liberada havendo parcelas vencidas..
        /// </summary>
        internal static string _0088 {
            get {
                return ResourceManager.GetString("_0088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contratos cancelados só podem ser editados pelo departamento financeiro..
        /// </summary>
        internal static string _0089 {
            get {
                return ResourceManager.GetString("_0089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senhas não conferem.
        /// </summary>
        internal static string _0090 {
            get {
                return ResourceManager.GetString("_0090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize a abertura do contrato antes de liberar acessos..
        /// </summary>
        internal static string _0091 {
            get {
                return ResourceManager.GetString("_0091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Atualizado com sucesso..
        /// </summary>
        internal static string _0092 {
            get {
                return ResourceManager.GetString("_0092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email incluido com sucesso.
        /// </summary>
        internal static string _0093 {
            get {
                return ResourceManager.GetString("_0093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberação de acesso Ok..
        /// </summary>
        internal static string _0094 {
            get {
                return ResourceManager.GetString("_0094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular já possui acesso ao contrato..
        /// </summary>
        internal static string _0095 {
            get {
                return ResourceManager.GetString("_0095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato reativado com sucesso..
        /// </summary>
        internal static string _0096 {
            get {
                return ResourceManager.GetString("_0096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma parcela antes de continuar..
        /// </summary>
        internal static string _0097 {
            get {
                return ResourceManager.GetString("_0097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente parcelas &quot;Geradas&quot; podem ter a lista de produtos editadas..
        /// </summary>
        internal static string _0098 {
            get {
                return ResourceManager.GetString("_0098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um produto antes de continuar..
        /// </summary>
        internal static string _0099 {
            get {
                return ResourceManager.GetString("_0099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este contrato possui pendencias financeiras que impedem que ele seja reativado, favor verificar com o financeiro..
        /// </summary>
        internal static string _0100 {
            get {
                return ResourceManager.GetString("_0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este contrato é do tipo {0}, não pode ser editado por esta tela..
        /// </summary>
        internal static string _0101 {
            get {
                return ResourceManager.GetString("_0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Status do contrato é {0}, impossibilita de Emitir Boleto junto ao banco..
        /// </summary>
        internal static string _0102 {
            get {
                return ResourceManager.GetString("_0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique se digitou o contato {0} com DDD.
        /// </summary>
        internal static string _0103 {
            get {
                return ResourceManager.GetString("_0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma parcela antes de continuar..
        /// </summary>
        internal static string _0104 {
            get {
                return ResourceManager.GetString("_0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário sem privilégio..
        /// </summary>
        internal static string _0105 {
            get {
                return ResourceManager.GetString("_0105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente o Clube Conteza pode oferecer desconto maior que o liberado de {0}..
        /// </summary>
        internal static string _0106 {
            get {
                return ResourceManager.GetString("_0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconto maior que 100% não é permitido..
        /// </summary>
        internal static string _0107 {
            get {
                return ResourceManager.GetString("_0107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessario pelo menos {0} parcelas em atrazo para oferecer desconto a vista..
        /// </summary>
        internal static string _0108 {
            get {
                return ResourceManager.GetString("_0108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo {0} só pode conter numeros..
        /// </summary>
        internal static string _0109 {
            get {
                return ResourceManager.GetString("_0109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo {0} esta com a quantidade invalida de caracteres..
        /// </summary>
        internal static string _0110 {
            get {
                return ResourceManager.GetString("_0110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premio já foi contemplado, não pode mais ser sorteado..
        /// </summary>
        internal static string _0111 {
            get {
                return ResourceManager.GetString("_0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premiação cancelada, não pode ser sorteado..
        /// </summary>
        internal static string _0112 {
            get {
                return ResourceManager.GetString("_0112", resourceCulture);
            }
        }
    }
}
